# Generated by Django 5.0.4 on 2024-04-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Populaton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
                ('Human_count', models.IntegerField()),
            ],
        ),
    ]
